const express = require("express");
const router = express.Router();
const buyNsell = require("../controller/buyNsellController");
const crypto = require("crypto");

router.post("/login", buyNsell.login);
router.post("/verify-otp", buyNsell.verifyOtp);
router.post("/resend-otp", buyNsell.resendOtp);
router.post("/request-password-reset", buyNsell.requestPasswordReset);
router.post("/verify-reset-code", buyNsell.verifyResetCode);
router.post("/reset-password", buyNsell.resetPassword);
router.post("/register", buyNsell.register);
router.post("/verify-register-otp", buyNsell.verifyRegisterOtp);
router.post("/", buyNsell.token);
router.delete("/", buyNsell.delToken);
router.post("/profile", buyNsell.profile);
router.post("/deleteAccount", buyNsell.delAcc);
router.get("/users/:id/verify/:token", buyNsell.verify);
router.post("/logout", buyNsell.logout);
router.post("/allprod", buyNsell.displayProd);
router.post("/sell", buyNsell.sell);
router.post("/admin/pending-products", buyNsell.getPendingProducts);
router.post("/admin/approve-product", buyNsell.approveProduct);
router.post("/admin/reject-product", buyNsell.rejectProduct);
router.post("/update", buyNsell.update);
router.post("/prodData", buyNsell.prodData);
router.post("/searchproduct", buyNsell.searchproduct);
router.post("/addbid", buyNsell.addbid);
router.post("/acceptbid", buyNsell.acceptbid);
router.post("/rejectbid", buyNsell.rejectbid);
router.post("/fixdeal", buyNsell.fixdeal);
router.post("/removebid", buyNsell.removebid);
router.post("/confirmdeal", buyNsell.confirmdeal);
router.post("/cancelnotification", buyNsell.cancelnotification);
router.post("/deletemyprod", buyNsell.deletemyprod);
router.post("/deletemybid", buyNsell.deletemybid);
router.post("/sendMessage", buyNsell.sendMessage);
router.post("/getMessages", buyNsell.getMessages);
router.post("/getChatList", buyNsell.getChatList);
module.exports = router;
